version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: init.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: validate.sh
      timeout: 200
      runas: ec2-user